//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace popovms.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int id { get; set; }
        public Nullable<int> id_post { get; set; }
        public string surname { get; set; }
        public string name { get; set; }
        public string middlename { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> Last_entry { get; set; }
        public Nullable<int> type_entrance { get; set; }
        public string image { get; set; }
    
        public virtual post post { get; set; }
        public virtual type_entrance type_entrance1 { get; set; }
    }
}
