//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace popovms.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public orders()
        {
            this.services_orders = new HashSet<services_orders>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> date_add { get; set; }
        public Nullable<System.TimeSpan> time_orders { get; set; }
        public Nullable<int> id_client { get; set; }
        public Nullable<int> id_status { get; set; }
        public Nullable<System.DateTime> date_closing { get; set; }
        public Nullable<int> time_rental { get; set; }
    
        public virtual client client { get; set; }
        public virtual status status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<services_orders> services_orders { get; set; }
    }
}
