//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace popovms.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class services_orders
    {
        public int id { get; set; }
        public Nullable<int> id_orders { get; set; }
        public Nullable<int> id_services { get; set; }
    
        public virtual orders orders { get; set; }
        public virtual services services { get; set; }
    }
}
